# Alembic Configuration File
[alembic]
script_location = .

# Template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# Sys.path path, will be prepended to sys.path if present
prepend_sys_path = .

sqlalchemy.url = postgresql://

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
