/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRecommendationsRouteImport } from './routes/_protected/recommendations'
import { Route as ProtectedProgressRouteImport } from './routes/_protected/progress'
import { Route as ProtectedHistoryRouteImport } from './routes/_protected/history'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedChallengesRouteImport } from './routes/_protected/challenges'
import { Route as ProtectedResultsIdRouteImport } from './routes/_protected/results.$id'
import { Route as ProtectedMissionIdRouteImport } from './routes/_protected/mission.$id'
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/admin/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRecommendationsRoute =
  ProtectedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProgressRoute = ProtectedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHistoryRoute = ProtectedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChallengesRoute = ProtectedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedResultsIdRoute = ProtectedResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMissionIdRoute = ProtectedMissionIdRouteImport.update({
  id: '/mission/$id',
  path: '/mission/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/challenges': typeof ProtectedChallengesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/history': typeof ProtectedHistoryRoute
  '/progress': typeof ProtectedProgressRoute
  '/recommendations': typeof ProtectedRecommendationsRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/mission/$id': typeof ProtectedMissionIdRoute
  '/results/$id': typeof ProtectedResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/challenges': typeof ProtectedChallengesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/history': typeof ProtectedHistoryRoute
  '/progress': typeof ProtectedProgressRoute
  '/recommendations': typeof ProtectedRecommendationsRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/mission/$id': typeof ProtectedMissionIdRoute
  '/results/$id': typeof ProtectedResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/challenges': typeof ProtectedChallengesRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/history': typeof ProtectedHistoryRoute
  '/_protected/progress': typeof ProtectedProgressRoute
  '/_protected/recommendations': typeof ProtectedRecommendationsRoute
  '/_protected/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/_protected/mission/$id': typeof ProtectedMissionIdRoute
  '/_protected/results/$id': typeof ProtectedResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/challenges'
    | '/dashboard'
    | '/history'
    | '/progress'
    | '/recommendations'
    | '/admin/dashboard'
    | '/mission/$id'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/challenges'
    | '/dashboard'
    | '/history'
    | '/progress'
    | '/recommendations'
    | '/admin/dashboard'
    | '/mission/$id'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/challenges'
    | '/_protected/dashboard'
    | '/_protected/history'
    | '/_protected/progress'
    | '/_protected/recommendations'
    | '/_protected/admin/dashboard'
    | '/_protected/mission/$id'
    | '/_protected/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/recommendations': {
      id: '/_protected/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof ProtectedRecommendationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/progress': {
      id: '/_protected/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProtectedProgressRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/history': {
      id: '/_protected/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ProtectedHistoryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/challenges': {
      id: '/_protected/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ProtectedChallengesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/results/$id': {
      id: '/_protected/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ProtectedResultsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/mission/$id': {
      id: '/_protected/mission/$id'
      path: '/mission/$id'
      fullPath: '/mission/$id'
      preLoaderRoute: typeof ProtectedMissionIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/dashboard': {
      id: '/_protected/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedChallengesRoute: typeof ProtectedChallengesRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedHistoryRoute: typeof ProtectedHistoryRoute
  ProtectedProgressRoute: typeof ProtectedProgressRoute
  ProtectedRecommendationsRoute: typeof ProtectedRecommendationsRoute
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute
  ProtectedMissionIdRoute: typeof ProtectedMissionIdRoute
  ProtectedResultsIdRoute: typeof ProtectedResultsIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedChallengesRoute: ProtectedChallengesRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedHistoryRoute: ProtectedHistoryRoute,
  ProtectedProgressRoute: ProtectedProgressRoute,
  ProtectedRecommendationsRoute: ProtectedRecommendationsRoute,
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedMissionIdRoute: ProtectedMissionIdRoute,
  ProtectedResultsIdRoute: ProtectedResultsIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
