/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRecommendationsRouteImport } from './routes/_protected/recommendations'
import { Route as ProtectedProgressRouteImport } from './routes/_protected/progress'
import { Route as ProtectedHistoryRouteImport } from './routes/_protected/history'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedChallengesRouteImport } from './routes/_protected/challenges'
import { Route as ProtectedResultsIdRouteImport } from './routes/_protected/results.$id'
import { Route as ProtectedMissionIdRouteImport } from './routes/_protected/mission.$id'
import { Route as ProtectedFeedbackIdRouteImport } from './routes/_protected/feedback.$id'
import { Route as ProtectedAdminSessionsRouteImport } from './routes/_protected/admin/sessions'
import { Route as ProtectedAdminPolicyRouteImport } from './routes/_protected/admin/policy'
import { Route as ProtectedAdminPlaygroundRouteImport } from './routes/_protected/admin/playground'
import { Route as ProtectedAdminMissionsRouteImport } from './routes/_protected/admin/missions'
import { Route as ProtectedAdminLearnersRouteImport } from './routes/_protected/admin/learners'
import { Route as ProtectedAdminFailuresRouteImport } from './routes/_protected/admin/failures'
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/admin/dashboard'
import { Route as ProtectedAdmin_layoutRouteImport } from './routes/_protected/admin/__layout'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRecommendationsRoute =
  ProtectedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProgressRoute = ProtectedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHistoryRoute = ProtectedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChallengesRoute = ProtectedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedResultsIdRoute = ProtectedResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMissionIdRoute = ProtectedMissionIdRouteImport.update({
  id: '/mission/$id',
  path: '/mission/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFeedbackIdRoute = ProtectedFeedbackIdRouteImport.update({
  id: '/feedback/$id',
  path: '/feedback/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminSessionsRoute = ProtectedAdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminPolicyRoute = ProtectedAdminPolicyRouteImport.update({
  id: '/admin/policy',
  path: '/admin/policy',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminPlaygroundRoute =
  ProtectedAdminPlaygroundRouteImport.update({
    id: '/admin/playground',
    path: '/admin/playground',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminMissionsRoute = ProtectedAdminMissionsRouteImport.update({
  id: '/admin/missions',
  path: '/admin/missions',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminLearnersRoute = ProtectedAdminLearnersRouteImport.update({
  id: '/admin/learners',
  path: '/admin/learners',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminFailuresRoute = ProtectedAdminFailuresRouteImport.update({
  id: '/admin/failures',
  path: '/admin/failures',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdmin_layoutRoute = ProtectedAdmin_layoutRouteImport.update({
  id: '/admin/__layout',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/challenges': typeof ProtectedChallengesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/history': typeof ProtectedHistoryRoute
  '/progress': typeof ProtectedProgressRoute
  '/recommendations': typeof ProtectedRecommendationsRoute
  '/admin': typeof ProtectedAdmin_layoutRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/admin/failures': typeof ProtectedAdminFailuresRoute
  '/admin/learners': typeof ProtectedAdminLearnersRoute
  '/admin/missions': typeof ProtectedAdminMissionsRoute
  '/admin/playground': typeof ProtectedAdminPlaygroundRoute
  '/admin/policy': typeof ProtectedAdminPolicyRoute
  '/admin/sessions': typeof ProtectedAdminSessionsRoute
  '/feedback/$id': typeof ProtectedFeedbackIdRoute
  '/mission/$id': typeof ProtectedMissionIdRoute
  '/results/$id': typeof ProtectedResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/challenges': typeof ProtectedChallengesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/history': typeof ProtectedHistoryRoute
  '/progress': typeof ProtectedProgressRoute
  '/recommendations': typeof ProtectedRecommendationsRoute
  '/admin': typeof ProtectedAdmin_layoutRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/admin/failures': typeof ProtectedAdminFailuresRoute
  '/admin/learners': typeof ProtectedAdminLearnersRoute
  '/admin/missions': typeof ProtectedAdminMissionsRoute
  '/admin/playground': typeof ProtectedAdminPlaygroundRoute
  '/admin/policy': typeof ProtectedAdminPolicyRoute
  '/admin/sessions': typeof ProtectedAdminSessionsRoute
  '/feedback/$id': typeof ProtectedFeedbackIdRoute
  '/mission/$id': typeof ProtectedMissionIdRoute
  '/results/$id': typeof ProtectedResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/challenges': typeof ProtectedChallengesRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/history': typeof ProtectedHistoryRoute
  '/_protected/progress': typeof ProtectedProgressRoute
  '/_protected/recommendations': typeof ProtectedRecommendationsRoute
  '/_protected/admin/__layout': typeof ProtectedAdmin_layoutRoute
  '/_protected/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/_protected/admin/failures': typeof ProtectedAdminFailuresRoute
  '/_protected/admin/learners': typeof ProtectedAdminLearnersRoute
  '/_protected/admin/missions': typeof ProtectedAdminMissionsRoute
  '/_protected/admin/playground': typeof ProtectedAdminPlaygroundRoute
  '/_protected/admin/policy': typeof ProtectedAdminPolicyRoute
  '/_protected/admin/sessions': typeof ProtectedAdminSessionsRoute
  '/_protected/feedback/$id': typeof ProtectedFeedbackIdRoute
  '/_protected/mission/$id': typeof ProtectedMissionIdRoute
  '/_protected/results/$id': typeof ProtectedResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/challenges'
    | '/dashboard'
    | '/history'
    | '/progress'
    | '/recommendations'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/failures'
    | '/admin/learners'
    | '/admin/missions'
    | '/admin/playground'
    | '/admin/policy'
    | '/admin/sessions'
    | '/feedback/$id'
    | '/mission/$id'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/challenges'
    | '/dashboard'
    | '/history'
    | '/progress'
    | '/recommendations'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/failures'
    | '/admin/learners'
    | '/admin/missions'
    | '/admin/playground'
    | '/admin/policy'
    | '/admin/sessions'
    | '/feedback/$id'
    | '/mission/$id'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/challenges'
    | '/_protected/dashboard'
    | '/_protected/history'
    | '/_protected/progress'
    | '/_protected/recommendations'
    | '/_protected/admin/__layout'
    | '/_protected/admin/dashboard'
    | '/_protected/admin/failures'
    | '/_protected/admin/learners'
    | '/_protected/admin/missions'
    | '/_protected/admin/playground'
    | '/_protected/admin/policy'
    | '/_protected/admin/sessions'
    | '/_protected/feedback/$id'
    | '/_protected/mission/$id'
    | '/_protected/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/recommendations': {
      id: '/_protected/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof ProtectedRecommendationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/progress': {
      id: '/_protected/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProtectedProgressRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/history': {
      id: '/_protected/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ProtectedHistoryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/challenges': {
      id: '/_protected/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ProtectedChallengesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/results/$id': {
      id: '/_protected/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ProtectedResultsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/mission/$id': {
      id: '/_protected/mission/$id'
      path: '/mission/$id'
      fullPath: '/mission/$id'
      preLoaderRoute: typeof ProtectedMissionIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/feedback/$id': {
      id: '/_protected/feedback/$id'
      path: '/feedback/$id'
      fullPath: '/feedback/$id'
      preLoaderRoute: typeof ProtectedFeedbackIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/sessions': {
      id: '/_protected/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof ProtectedAdminSessionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/policy': {
      id: '/_protected/admin/policy'
      path: '/admin/policy'
      fullPath: '/admin/policy'
      preLoaderRoute: typeof ProtectedAdminPolicyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/playground': {
      id: '/_protected/admin/playground'
      path: '/admin/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof ProtectedAdminPlaygroundRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/missions': {
      id: '/_protected/admin/missions'
      path: '/admin/missions'
      fullPath: '/admin/missions'
      preLoaderRoute: typeof ProtectedAdminMissionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/learners': {
      id: '/_protected/admin/learners'
      path: '/admin/learners'
      fullPath: '/admin/learners'
      preLoaderRoute: typeof ProtectedAdminLearnersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/failures': {
      id: '/_protected/admin/failures'
      path: '/admin/failures'
      fullPath: '/admin/failures'
      preLoaderRoute: typeof ProtectedAdminFailuresRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/dashboard': {
      id: '/_protected/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/__layout': {
      id: '/_protected/admin/__layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdmin_layoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedChallengesRoute: typeof ProtectedChallengesRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedHistoryRoute: typeof ProtectedHistoryRoute
  ProtectedProgressRoute: typeof ProtectedProgressRoute
  ProtectedRecommendationsRoute: typeof ProtectedRecommendationsRoute
  ProtectedAdmin_layoutRoute: typeof ProtectedAdmin_layoutRoute
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute
  ProtectedAdminFailuresRoute: typeof ProtectedAdminFailuresRoute
  ProtectedAdminLearnersRoute: typeof ProtectedAdminLearnersRoute
  ProtectedAdminMissionsRoute: typeof ProtectedAdminMissionsRoute
  ProtectedAdminPlaygroundRoute: typeof ProtectedAdminPlaygroundRoute
  ProtectedAdminPolicyRoute: typeof ProtectedAdminPolicyRoute
  ProtectedAdminSessionsRoute: typeof ProtectedAdminSessionsRoute
  ProtectedFeedbackIdRoute: typeof ProtectedFeedbackIdRoute
  ProtectedMissionIdRoute: typeof ProtectedMissionIdRoute
  ProtectedResultsIdRoute: typeof ProtectedResultsIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedChallengesRoute: ProtectedChallengesRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedHistoryRoute: ProtectedHistoryRoute,
  ProtectedProgressRoute: ProtectedProgressRoute,
  ProtectedRecommendationsRoute: ProtectedRecommendationsRoute,
  ProtectedAdmin_layoutRoute: ProtectedAdmin_layoutRoute,
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedAdminFailuresRoute: ProtectedAdminFailuresRoute,
  ProtectedAdminLearnersRoute: ProtectedAdminLearnersRoute,
  ProtectedAdminMissionsRoute: ProtectedAdminMissionsRoute,
  ProtectedAdminPlaygroundRoute: ProtectedAdminPlaygroundRoute,
  ProtectedAdminPolicyRoute: ProtectedAdminPolicyRoute,
  ProtectedAdminSessionsRoute: ProtectedAdminSessionsRoute,
  ProtectedFeedbackIdRoute: ProtectedFeedbackIdRoute,
  ProtectedMissionIdRoute: ProtectedMissionIdRoute,
  ProtectedResultsIdRoute: ProtectedResultsIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
